import { describe, expect, it } from "vitest";
import fixtures from "./__fixtures__/geometry.json";
import { angleDiff, curve, degToCompass, inArc } from "./geometry";

/**
 * Parity test: the fixture is generated by `scripts/gen-geometry-fixtures.py`
 * from `surfcheck/geometry.py` (the source of truth). If the TS port and the
 * Python module disagree on any input we'll catch it here.
 */
describe("geometry parity vs surfcheck.geometry", () => {
  it("degToCompass matches Python for the fixture set", () => {
    for (const { deg, label } of fixtures.degToCompass) {
      expect(degToCompass(deg), `deg=${deg}`).toBe(label);
    }
  });

  it("angleDiff matches Python for the fixture set", () => {
    for (const { a, b, diff } of fixtures.angleDiff) {
      expect(angleDiff(a, b), `a=${a}, b=${b}`).toBeCloseTo(diff, 10);
    }
  });

  it("inArc matches Python for the fixture set", () => {
    for (const { deg, start, end, result } of fixtures.inArc) {
      expect(inArc(deg, start, end), `deg=${deg} arc=[${start},${end}]`).toBe(
        result,
      );
    }
  });

  it("curve matches Python for the fixture set", () => {
    const points = fixtures.curve.points.map(([t, s]) => [t, s] as const);
    for (const { value, score } of fixtures.curve.samples) {
      expect(curve(value, points), `value=${value}`).toBe(score);
    }
  });
});

describe("geometry edge cases", () => {
  it("degToCompass wraps the 16-point circle", () => {
    expect(degToCompass(0)).toBe("N");
    expect(degToCompass(90)).toBe("E");
    expect(degToCompass(180)).toBe("S");
    expect(degToCompass(270)).toBe("W");
    expect(degToCompass(360)).toBe("N");
  });

  it("angleDiff returns 0..180", () => {
    for (let a = 0; a < 360; a += 17) {
      for (let b = 0; b < 360; b += 23) {
        const d = angleDiff(a, b);
        expect(d).toBeGreaterThanOrEqual(0);
        expect(d).toBeLessThanOrEqual(180);
      }
    }
  });

  it("inArc handles wrap-around at 360", () => {
    expect(inArc(0, 350, 10)).toBe(true);
    expect(inArc(180, 350, 10)).toBe(false);
  });

  it("curve returns 0 when value exceeds every threshold", () => {
    expect(curve(1000, [[1, 5], [10, 3]])).toBe(0);
  });
});
