// Angular and curve utilities — TS port of surfcheck/geometry.py.
// Pure functions, side-effect free. Used by UI for direction labels
// (deg_to_compass) and as a parity reference against the Python module.
// Behavior must match the Python source byte-for-byte; lib/geometry.test.ts
// asserts that against a JSON fixture generated by scripts/gen-geometry-fixtures.py.

const COMPASS_EN = [
  "N",
  "NNE",
  "NE",
  "ENE",
  "E",
  "ESE",
  "SE",
  "SSE",
  "S",
  "SSW",
  "SW",
  "WSW",
  "W",
  "WNW",
  "NW",
  "NNW",
] as const;

/**
 * Convert degrees (any number) to a 16-point compass label (English: N..NNW).
 * Matches the Python implementation's index arithmetic exactly:
 *     COMPASS[int((d % 360) / 22.5 + 0.5) % 16]
 *
 * Python's `%` on floats returns a non-negative result for positive moduli,
 * and `int()` truncates toward zero — we mirror both with mod() + Math.trunc.
 */
export function degToCompass(d: number): (typeof COMPASS_EN)[number] {
  const idx = Math.trunc(mod(d, 360) / 22.5 + 0.5) % 16;
  return COMPASS_EN[idx];
}

/**
 * Smallest angular distance between two directions, 0..180.
 * Python: `abs(((a - b + 180) % 360) - 180)`
 */
export function angleDiff(a: number, b: number): number {
  return Math.abs(mod(a - b + 180, 360) - 180);
}

/**
 * True if `deg` falls inside the arc [start, end] (degrees, 0..360),
 * with wrap-around when end < start.
 */
export function inArc(deg: number, start: number, end: number): boolean {
  const d = mod(deg, 360);
  if (start <= end) return d >= start && d <= end;
  return d >= start || d <= end;
}

export type CurvePoint = readonly [threshold: number, score: number];

/**
 * Step-curve lookup: returns the score for the first (threshold, score)
 * tuple whose `threshold > value`. Returns 0 if no tuple matches.
 * Matches `surfcheck.geometry.curve`.
 */
export function curve(value: number, points: readonly CurvePoint[]): number {
  for (const [thr, sc] of points) {
    if (value < thr) return sc;
  }
  return 0;
}

/** Python-style modulo: always non-negative when modulus is positive. */
function mod(a: number, n: number): number {
  return ((a % n) + n) % n;
}
